[package]
name = "hill_vacuum_shared"
version = "0.2.5"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Library of shared utilities among the other HillVacuum libraries"
readme = "README.md"
keywords = ["gamedev", "mapeditor", "bevy"]
